### ISSUE TITLE
forward logged exceptions to Error Reporting

### ISSUE THREAD

**Issue by aknow90336** [manigandham/serilog-sinks-googlecloudlogging#54] opened 2021-09-10 03:22 UTC
Hi i alrady set ServiceName and ServiceVersion 

```
var option= new GoogleCloudLoggingSinkOptions
{
    ServiceName = "TestService",
    LogName = "TestLog",
    ServiceVersion = "1.0",
    ResourceType = "generic_task",
    UseJsonOutput = true,
};
```
![image](https://user-images.githubusercontent.com/23616301/132793886-627bb00c-993d-4cc2-b432-69f0b87a74a6.png)
But my Error Reporting didn't receive any event 
![image](https://user-images.githubusercontent.com/23616301/132794301-08ec0028-5068-4921-9cf2-c3068715787b.png)
please tell me how can i forward it Thanks~~~

**Comment by manigandham** [comment] 2021-09-10 03:34
Can you try setting `UseLogCorrelation` to true? If that doesn’t work then I can debug later

**Comment by aknow90336** [comment] 2021-09-10 03:44
i set `UseLogCorrelation` but nothing change QQ

**Comment by manigandham** [comment] 2021-09-10 06:13
How are you logging the error? Is this an `Exception` object that you caught and are logging or is it just an error message directly? 

This is an example of the error logging: 
https://github.com/manigandham/serilog-sinks-googlecloudlogging/blob/master/src/TestWeb/HomeController.cs#L56

**Comment by aknow90336** [comment] 2021-09-10 06:44
I use middleware handle global error

`public class ExceptionMiddleware
    {
        private readonly RequestDelegate _next;

        private readonly ILogger _logger;

        public ExceptionMiddleware(RequestDelegate next, ILoggerFactory loggerFactory)
        {
            _next = next;
            _logger = loggerFactory.CreateLogger<ExceptionMiddleware>();
        }

        public async Task Invoke(HttpContext context)
        {
            try
            {
                await _next.Invoke(context);
            }
            catch (Exception ex)
            {
                string errorJson = JsonSerializer.Serialize(new
                {
                    message = "system error",
                    code = "9999"
                });
                
                _logger.LogError(ex, ex.ToString());
                await HandleExceptionAsync(context, errorJson);
            }
        }
    }`

**Comment by manigandham** [comment] 2021-09-10 20:26
The issue is your resource type is set to `generic_task` and this is not a supported resource type for error logging. You can find the supported list here: https://cloud.google.com/error-reporting/docs/formatting-error-messages#supported_monitored_resource_types

**Comment by aknow90336** [comment] 2021-09-11 02:28
ops that’s correct.
thank u very much~~~~

**Comment by manigandham** [comment] 2021-09-11 03:03
Great, closing this issue now.

**Closed by manigandham** 2021-09-11 03:03 UTC
